apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-slave-deployment
  labels:
    app: db-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db-slave
  template:
    metadata:
      labels:
        app: db-slave
    spec:
      containers:
      - name: db-slave
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: orders_db
        volumeMounts:
        - name: db-slave-data
          mountPath: /var/lib/postgresql/data
        command:
        - "bash"
        - "-c"
        - |
          echo 'Waiting for master database to start...';
          while ! pg_isready -h db-master-service -p 5432; do sleep 1; done;
          echo 'Setting up replication...';
          rm -rf /var/lib/postgresql/data/*;
          PGPASSWORD=password pg_basebackup -h db-master-service -p 5432 -U replicator -D /var/lib/postgresql/data -Fp -Xs -P;
          touch /var/lib/postgresql/data/standby.signal;
          echo "primary_conninfo = 'host=db-master-service port=5432 user=replicator password=password'" >> /var/lib/postgresql/data/postgresql.auto.conf;
          echo 'Replication setup complete. Starting slave database...';
          docker-entrypoint.sh postgres
      volumes:
      - name: db-slave-data
        emptyDir: {}
