version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DB_MASTER_HOST: db-master-service
      DB_SLAVE_HOST: db-slave-service
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: orders_db
      DB_PORT: 5432
    networks:
      - db-network

volumes:
  db-master-data:
  db-slave-data:

networks:
  db-network:
    driver: bridge
