apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.appPort }}
    targetPort: 3000
  selector:
    app: app
